# Generated by Django 2.2.4 on 2019-09-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Chassis',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ESN',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Engine_Model',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
