# Generated by Django 2.2.4 on 2019-09-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20190902_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Engine_Family',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Engine_Year',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
