# Generated by Django 2.2.4 on 2019-09-02 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20190902_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Machining_Assembly',
            new_name='After_Treatment_Softwate_Level',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='Software_Level',
            new_name='Current_Software_Level',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='Engine_Model',
            new_name='Mileage',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='Engine_Year',
            new_name='Model_Year',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Last_Software_Level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Rear_Axle_Ratio',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('publish', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Vehicle')),
            ],
            options={
                'verbose_name': 'PlantData',
                'verbose_name_plural': 'PlantDatas',
            },
        ),
        migrations.CreateModel(
            name='CEPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('publish', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Vehicle')),
            ],
            options={
                'verbose_name': 'CEPData',
                'verbose_name_plural': 'CEPDatas',
            },
        ),
    ]
