# Generated by Django 2.2.4 on 2019-09-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20190902_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cepdata',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cepdata',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='plantdata',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='cepdata',
            name='BOEC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cepdata',
            name='Chassis',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='cepdata',
            name='Current_Software_Level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cepdata',
            name='ESN',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='cepdata',
            name='Engine_Family',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cepdata',
            name='HP_Rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cepdata',
            name='Last_Software_Level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cepdata',
            name='Model_Year',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cepdata',
            name='Truck_Model',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='After_Treatment_Softwate_Level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='Application',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='CEPData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.CEPData'),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='Mileage',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='Rear_Axle_Ratio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plantdata',
            name='Transmission_Configuration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
