# Generated by Django 2.2.4 on 2019-09-02 11:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20190902_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('SLID', models.CharField(default='', max_length=255, unique=True)),
                ('Disposition', models.TextField(blank=True, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('publish', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'SLCase',
                'verbose_name_plural': 'SLCases',
            },
        ),
        migrations.RemoveField(
            model_name='plantdata',
            name='order',
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('File_Name', models.CharField(default='', max_length=255)),
                ('File_Type', models.CharField(default='', max_length=255)),
                ('File_Size', models.CharField(default='', max_length=255)),
                ('File', models.FileField(upload_to='uploads/')),
                ('Description', models.TextField(blank=True, null=True)),
                ('publish', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('SLCase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.SLCase')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
