# Generated by Django 2.2.4 on 2019-09-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20190902_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='File',
            new_name='Attachment',
        ),
        migrations.RenameField(
            model_name='attachments',
            old_name='File_Name',
            new_name='Type_Code',
        ),
        migrations.RemoveField(
            model_name='attachments',
            name='File_Size',
        ),
        migrations.RemoveField(
            model_name='attachments',
            name='File_Type',
        ),
    ]
