# Generated by Django 2.2.4 on 2019-09-03 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20190903_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('publish', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
            },
        ),
        migrations.RenameModel(
            old_name='Attachments',
            new_name='Attachment',
        ),
    ]
