# Generated by Django 2.2.4 on 2019-09-03 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20190903_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davie_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('publish', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Davie Log',
                'verbose_name_plural': 'Davie Logs',
            },
        ),
        migrations.CreateModel(
            name='Fault_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('publish', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Fault Code',
                'verbose_name_plural': 'Fault Codes',
            },
        ),
    ]
