# Generated by Django 2.2.4 on 2019-09-03 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_auto_20190903_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cepdata',
            name='Engine_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
