# Generated by Django 2.2.4 on 2019-09-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_auto_20190903_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='CEPData',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='panel.CEPData'),
        ),
    ]
