# Generated by Django 2.2.4 on 2019-09-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_auto_20190903_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='After_Treatment_Softwate_Level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='Application',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='Mileage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='Rear_Axle_Ratio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='Transmission_Configuration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
