# Generated by Django 2.2.4 on 2019-09-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_auto_20190903_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantdata',
            old_name='CEPData',
            new_name='cep',
        ),
    ]
