# Generated by Django 2.2.4 on 2019-09-03 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_auto_20190903_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('cep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='panel.CEPData')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('Service_Date', models.DateField(default=datetime.date.today)),
                ('Mileage', models.IntegerField(blank=True, null=True)),
                ('publish', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
