# Generated by Django 2.2.4 on 2019-09-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='cep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.CEPData'),
        ),
    ]
